adi-yeltay pr
talgat-ruby/exercises-go pull request #12
Opened 2024-05-30 07:25 UTC by yltyadi

2024-06-01 07:26 UTC, talgat-ruby requested changes
Please complete all required exercises.

2024-06-01 07:26 UTC, talgat-ruby commented on exercise1/problem5/README.md
Why did you update it? Please revert.

2024-06-01 13:56 UTC, yltyadi commented
fixed problem 5, all required tasks are compiling now

2024-06-02 14:04 UTC, yltyadi commented on exercise1/problem5/README.md
completed all required exercises, only problem 3 left which is optional

2024-06-25 08:01 UTC, talgat-ruby commented
@yltyadi  Please pass all required tests

2024-06-25 12:07 UTC, yltyadi commented
@talgat-ruby can you please run the tests again, now it should work, but I changed ex2/problem7 test cases

2024-06-26 15:07 UTC, talgat-ruby approved these changes
Well done!

2024-06-26 15:07 UTC, merged