exercise 1 sabit-kurmashev
talgat-ruby/exercises-go pull request #32
Opened 2024-06-02 19:10 UTC by ESKA17

2024-06-25 08:19 UTC, talgat-ruby requested changes
Please don't update test cases, they are correct!

2024-06-25 08:19 UTC, talgat-ruby commented on exercise1/problem10/problem10_test.go
> +	exp := map[string]int{"Hyundai": 5, "Kia": 0, "Toyota": 2}
please don't update test cases

2024-06-25 08:19 UTC, talgat-ruby commented on exercise2/problem4/problem4_test.go
> +			if f.value != row[2] || f.next.value != row[3] {
please don't update test cases

2024-06-25 08:19 UTC, talgat-ruby commented on exercise2/problem7/problem7_test.go
please don't update test cases

2024-07-02 10:51 UTC, ESKA17 commented on exercise3/problem1/.env
> -DB_PASSWORD="qYV=B=-x[S#$ccb"
в енвы контейнера с постгресом сажается пароль без концовки, начиная с доллара. В данном случае знак доллара и все, что идет после, считается за референс на другой не существующий енв вариабл в контейнере

2024-07-11 13:21 UTC, ESKA17 commented
Коммиты sabit-kurmashev exercise 1-4 не содержат изменений, кроме изменений в папках exercise1-4 (без затрагивания тестовых файлов)

2024-07-31 10:14 UTC, closed without merging